import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.scss";
import React from "react";
import Header from "../components/header/Header";
import Body from "../components/body/Body";
import Footer from "../components/footer/Footer";

export default function Home() {
  return (
    <div style={{ width: "100%" }}>
      <Head>
        <title>Git repo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div style={{ width: "100%" }}>
        <Body />
      </div>
      <Footer />
    </div>
  );
}
